pipeline:
  push-latest:
    image: plugins/docker
    settings:
      repo: redpencil/frontend-vliz-vocabserver
      tags: latest
    secrets: [ docker_username, docker_password ]
when:
  branch: master
  event: [ push ]
