steps:
  install:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm ci
  lint-js:
    image: danlynn/ember-cli:4.8.0
    group: lint
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:4.8.0
    group: lint
    commands:
      - npm run lint:hbs
  unused-components:
    image: danlynn/ember-cli:4.8.0
    group: lint
    commands:
      - npx ember-unused-components --fail-on-unused
    failure: ignore
  lint-dependencies:
    image: danlynn/ember-cli:4.8.0
    group: lint
    commands:
      - ember dependency-lint
    failure: ignore
  test:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm run test:ember
    failure: ignore
when:
  event: pull_request
